name: Sync with internal develop

on:
  workflow_dispatch:
  push:
    branches: 
    - develop

    
    
jobs:
  call-workflow-passing-data:
    if: ${{ github.repository == 'pbhandar-amd/rocm-install-on-linux' }}
    name: Sync
    uses: pbhandar-amd/rocm-docs-core/.github/workflows/merge_ff_only.yml@develop
    with:
      source-repo: pbhandar-amd/rocm-install-on-linux
      source-branch: develop
      target-repo: pbhandar-amd/rocm-install-on-linux-internal
      target-branch: develop
      env-name: Promotion
    secrets:
      github-token: ${{ secrets.GH_TOKEN }}
      
